name: Release Workflow

on:
  push:
    branches: [development, release-*]
  workflow_dispatch:
    inputs:
      promote:
        type: boolean
        description: Promote release to stable (for release-* branches only)
        default: false

permissions:
  contents: write
  id-token: write
  packages: write
  security-events: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: epam/ai-dial-ci/.github/workflows/node_release.yml@4.9.0
    with:
      docker-build-enabled: false
      node-version: '24'
      promote: ${{ inputs.promote || false }}
      publish-enabled: true
    secrets: inherit
